image: quay.io/fenicsproject/dev-env:latest

# Note: Our pipelines image does not work for DOLFIN because it's missing
# Boost, Eigen and possibly other packages.
#image: quay.io/fenicsproject/pipelines

pipelines:
  default:
    - step:
        script:
          - wget http://computation.llnl.gov/projects/sundials/download/sundials-2.7.0.tar.gz
          - tar xf sundials-2.7.0.tar.gz
          - mkdir -p sundials-2.7.0/build
          - cd sundials-2.7.0/build
          - cmake ..
          - make
          - make install
	  - cd ../..
          - pip2 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/instant.git@master
          - pip2 install git+https://bitbucket.org/fenics-project/ffc.git@master
          - mkdir -p build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=ON
          - make
          - make install
          - source /usr/local/share/dolfin/dolfin.conf
          - make run_quicktest
