version: 2
jobs:
  build:
    docker:
      - image: fenicsproject/pybind11-testing:latest
    working_directory: /home/fenics/working
    steps:
      - run:
          name: Clone DOLFIN
          command: git lfs clone https://bitbucket.org/"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}".git .
      - checkout
      - run:
          name: Install/update dependencies  # Install with sudo as tests not run as superuser in circleci/python
          command: |
            sudo pip3 install pytest six --upgrade
      - run:
          name: Install pybind11
          command: |
            git clone https://github.com/pybind/pybind11.git
            cd pybind11
            mkdir build-dir
            cd build-dir
            cmake -DPYBIND11_TEST=off ../
            sudo make install
      - run:
          name: Build Python interface
          command: |
            source /usr/local/share/dolfin/dolfin.conf
            cd python
            pip3 install . --user
      - run:
          name: Run tests (serial)
          command: |
            export PYTHONPATH=/usr/local/lib/python3.5/site-packages:$PWD/python/build/lib.linux-x86_64-3.5
            python3 -m pytest python/unit-tests
      - run:
          name: Run tests (MPI parallel)
          command: |
            export PYTHONPATH=/usr/local/lib/python3.5/site-packages:$PWD/python/build/lib.linux-x86_64-3.5
            mpirun -n 3 python3 -m pytest python/unit-tests
