version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      -run:
         command: mkdir -p workspace/local
      - persist_to_workspace:
        root: workspace
        paths:
         - local
      - run:
          name: Clone DOLFIN
          command: git lfs clone https://bitbucket.org/"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}".git .
      - checkout
      - run:
          name: Install FIAT
          command: ls -l && pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master --install-option="--prefix=/home/fenics/working/workspace/local"
  testpy11:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      - attach_workspace:
        at:  /home/fenics/working/workspace
      - checkout
      - run:
          name: Build pybind11 interface
          command: ls -lR workspace

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testpy11:
         requires:
           - build
         filters:
           branches:
             only: garth/feature-pybind11