version: 2
jobs:
  build:
    docker:
      - image: chrisrichardson/pybind11-testing:latest
    working_directory: /home/fenics/working
    steps:
      - run:
          name: Clone DOLFIN
          command: git lfs clone https://bitbucket.org/"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}".git .
      - checkout
      - run:
          name: Build pybind11
          command: source /usr/local/share/dolfin/dolfin.conf && cd python && git clone https://github.com/pybind/pybind11.git && python3 setup.py build
      - run:
          name: Test pybind11
          command: export PYTHONPATH=/usr/local/lib/python3.5/site-packages:$PWD/python/build/lib.linux-x86_64-3.5 && python3 -m pytest python/unit-tests
