version: 2
jobs:
  buildcpp:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      - checkout
      - run:
          name: Install FEniCS dependencies
          command: |
            if [ "${CIRCLE_BRANCH}" == "next" ] ; then export DEP_BRANCH_NAME="next" ; else export DEP_BRANCH_NAME="master" ; fi
            pip3 install --user git+https://bitbucket.org/fenics-project/fiat.git@"${DEP_BRANCH_NAME}"
            pip3 install --user git+https://bitbucket.org/fenics-project/ufl.git@"${DEP_BRANCH_NAME}"
            pip3 install --user git+https://bitbucket.org/fenics-project/dijitso.git@"${DEP_BRANCH_NAME}"
            pip3 install --user git+https://bitbucket.org/fenics-project/ffc.git@"${DEP_BRANCH_NAME}"
      - run:
          name: Configure DOLFIN (C++)
          command: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Developer ../
      - run:
          name: Build DOLFIN (C++)
          command: cd build && make -j2
      - persist_to_workspace:
          root: /home/fenics
          paths:
            - .local
            - working/build
  testcpp:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      - attach_workspace:
          at: /home/fenics
      - checkout
      - run:
          name: Build DOLFIN C++ documentation
          command: cd doc && doxygen
      - run:
          name: Build and run C++ unit tests (serial)
          command: cd build && make -j2 unittests && ctest -R unittests
      - run:
          name: Build and run C++ regressions tests (serial)
          command: cd build && make -j2 demos && ctest -j2 -R demo -R serial
      - run:
          name: Run C++ regression tests (MPI)
          command: cd build && make -j2 demos && ctest -R demo -R mpi
  buildpy:
    docker:
      - image: quay.io/fenicsproject/dev-env:latest
    working_directory: /home/fenics/working
    steps:
      - attach_workspace:
          at: /home/fenics
      - checkout
      - run:
          name: Install (already built) C++ DOLFIN
          command: cd build && make install
      - run:
          name: Install/update dependencies
          command: pip3 install --upgrade flake8 pytest pytest-xdist sphinx sphinx_rtd_theme
      - run:
          name: Flake8 checks on pybind11 Python code
          command: python3 -m flake8 python/dolfin
      - run:
          name: Build Python interface
          command: |
            cd python
            pip3 -v install . --user
      - run:
          name: Build DOLFIN Python documentation
          command: cd python/doc && make html
      - persist_to_workspace:
          root: /home/fenics
          paths:
            - working/python/doc/build/html/
      - run:
          name: Run Python unit tests (serial)
          command: python3 -m pytest -n 2 python/test/unit/
      - run:
          name: Run Python unit tests (MPI)
          command: mpirun -n 3 python3 -m pytest python/test/unit/
      - run:
          name: Generate Python demo (regression) programs
          command: python3 python/demo/generate-demo-files.py
      - run:
          name: Run Python regression tests (serial)
          command: python3 -m pytest -v -n2 python/demo/test.py
      - run:
          name: Run Python regression tests (MPI)
          command: python3 -m pytest -v python/demo/test.py --mpiexec=mpiexec --num-proc=3
  pushdoc:
    docker:
      - image: circleci/python
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Establish authenticity of fenicsproject.org
          command: mkdir -p ~/.ssh && echo "fenicsproject.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFbD134YcxSNaHVyio0XPAvJYh8SF90xp/ARqfrbAwOmJaEPTl5CNXm6f3+Sy0k1QTp+j9WawiJON+4/FWQBTD4=" >> ~/.ssh/known_hosts
      - run:
          name: Push Python API doc to fenicsproject.org
          command: cd /tmp/working/python/doc/build/html && scp -r * docs@fenicsproject.org:/var/www/vhosts/fenicsproject.org/docs/dolfin/dev/python/
workflows:
  version: 2
  build-and-pushdoc:
    jobs:
      - buildcpp
      - testcpp:
          requires:
            - buildcpp
      - buildpy:
          requires:
            - buildcpp
      - pushdoc:
          requires:
            - buildpy
          filters:
            branches:
              only:
                - master
